language:
  - python

python:
  - 3.5

install:
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - py.test -v preprocess.py --cov preprocess
  - coveralls

notifications:
  email: false

